[[docs]]
  name = "Prologue"
  weight = 3
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[book]]
  name = "序言"
  weight = 1
  identifier = "bprologue"
  url = "/book/prologue/"

[[main]]
  name = "书籍"
  url = "/book/prologue/introduction/"
  weight = 1
[[main]]
  name = "示例"
  url = "/demo/"
  weight = 2
[[main]]
  name = "4diac"
  url = "/docs/prologue/introduction/"
  weight = 3
[[main]]
  name = "硬件"
  url = "/hardware/"
  weight = 4
[[main]]
  name = "博客"
  url = "/blog/"
  weight = 20

# [[social]]
#   name = "Twitter"
#   pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#   url = "https://twitter.com/gethyas"
#   weight = 10



# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
